/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIDOMWindow;

[scriptable, uuid(6cd980fb-3fb6-4f15-b8fe-e0de557960f9)]
interface nsILocation4Evar : nsISupports
{
	readonly attribute boolean   advancedStatusDetectFullScreen;
	readonly attribute boolean   advancedStatusDetectVideo;
	readonly attribute boolean   advancedUrlbarForceBinding;

	readonly attribute boolean   firstRun;

	readonly attribute ACString  progressToolbarCSS;
	readonly attribute boolean   progressToolbarForce;
	readonly attribute boolean   progressToolbarStyle;
	readonly attribute boolean   progressToolbarStyleAdvanced;

	readonly attribute ACString  progressUrlbar;
	readonly attribute ACString  progressUrlbarCSS;
	readonly attribute boolean   progressUrlbarStyle;
	readonly attribute boolean   progressUrlbarStyleAdvanced;

	readonly attribute long      status;
	readonly attribute boolean   statusDefault;
	readonly attribute boolean   statusNetwork;
	readonly attribute boolean   statusNetworkXHR;
	readonly attribute long      statusTimeout;
	readonly attribute long      statusLinkOver;
	readonly attribute long      statusLinkOverDelayShow;
	readonly attribute long      statusLinkOverDelayHide;

	readonly attribute long      statusToolbarMaxLength;

	readonly attribute ACString  statusUrlbarAlign;
	readonly attribute ACString  statusUrlbarColor;
	readonly attribute long      statusUrlbarPosition;

	readonly attribute boolean   statusUrlbarInvertMirror;
	readonly attribute boolean   statusUrlbarMouseMirror;

	void resetPrefs();
	void updateWindow(in nsIDOMWindow win);
};

